version: '3.7'

services:

  wordpress:
    build:
      context: ./docker/wordpress
    ports:
      - "80:80"
    volumes:
      - ${VAGRANT_DEVCONTAINER_PATH}../wordpress:/var/www/html
      - ${VAGRANT_DEVCONTAINER_PATH}./docker/wordpress/php.ini:/usr/local/etc/php/php.ini
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      WORDPRESS_DB_USER: ${DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
      - ${VAGRANT_DEVCONTAINER_PATH}./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  wordmove:
    tty: true
    image: welaika/wordmove
    volumes:
      - ${VAGRANT_DEVCONTAINER_PATH}../wordpress:/var/www/html
      - ${VAGRANT_DEVCONTAINER_PATH}../wordmove:/home/wordmove
    environment:
      VM_HOSTNAME: "${VAGRANT_HOST}"
      PRODUCTION_URL: "${PRODUCTION_URL}"
      PRODUCTION_DIR_PATH: "${PRODUCTION_DIR_PATH}"
      PRODUCTION_DB_NAME: "${PRODUCTION_DB_NAME}"
      PRODUCTION_DB_USER: "${PRODUCTION_DB_USER}"
      PRODUCTION_DB_PASSWORD: "${PRODUCTION_DB_PASSWORD}"
      PRODUCTION_DB_HOST: "${PRODUCTION_DB_HOST}"
      PRODUCTION_DB_PORT: "${PRODUCTION_DB_PORT}"
      PRODUCTION_SSH_HOST: "${PRODUCTION_SSH_HOST}"
      PRODUCTION_SSH_PORT: "${PRODUCTION_SSH_PORT}"
      PRODUCTION_SSH_USER: "${PRODUCTION_SSH_USER}"
      PRODUCTION_SSH_PASSWORD: "${PRODUCTION_SSH_PASSWORD}"
      RUBYOPT: "-KU -E utf-8:utf-8"

    depends_on:
      - wordpress

volumes:
  mariadb:
    driver: local
